exclude: "^docs/source/conf.py$"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [ '--allow-missing-credentials']  # Avoid failure on BuildKite
    -   id: check-toml
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: check-json
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
        name: Shellcheck
        args: ["-f", "gcc"]  # output filename:linenum:colnum (clickable)
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
    hooks:
      - id: hadolint
        name: Hadolint (Dockerfile checker)
# Actual Python Linters
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black (Python formatter)
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (Python import sorter)
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Flake8 (Python linter)
        args: ["--output-file", "test_results/flake8.txt", "--tee", "src/", "tests/"]
        additional_dependencies:
          - "flake8-bandit==3.0.0"
          - "flake8-bugbear==22.3.23"
          - "flake8-docstrings==1.6.0"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        name: Mypy (Python type-checker)